### ISSUE TITLE
Missing witnessinfinite.csproj on build

### ISSUE THREAD

**Issue by Slerk3777** [Alith-Game-Studio/WhatTheWitness#3]
I downloaded the source code and imported it to godot 3.3.2, but when I tried to build it, it threw an error: 
```
Missing project file ./CSharpPuzNet/WitnessInfinite/WitnessInfinite.csproj
```
Could you please tell ne what witnessinfinite is and give a download to it? 
(I didn't find it in the sourcecode or the game)

**Comment by instr3** [comment]
Which branch are you using? The main branch should not require this file.

**Comment by Slerk3777** [comment]
The record-player branch.

**Comment by instr3** [comment]
This branch is for procedurally generated puzzle which requires some external dependency that could be tricky to configure. Besides, I am planning to remake it completely recently before make it public. If you are sure you want to work on it, leave me a Discord handle so I can add you to tell you how to do that.

**Comment by Slerk3777** [comment]
my discord is slerk3777.
(it's newly created btw, nvm)
I might have to check it tmr because I gotta go to bed soon.
